=== uo300548/SEW/xml/etapa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.uniovi.es"
           xmlns="http://www.uniovi.es"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">

  <xs:simpleType name="tipoEtapaType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="llana"/>
      <xs:enumeration value="montaña"/>
      <xs:enumeration value="contrarreloj individual"/>
      <xs:enumeration value="contrarreloj por equipos"/>
      <xs:enumeration value="media montaña"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="categoriaPuertoType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="1a"/>
      <xs:enumeration value="2a"/>
      <xs:enumeration value="3a"/>
      <xs:enumeration value="especial"/>
      <xs:enumeration value="bonificado"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tipoSprintType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="intermedio"/>
      <xs:enumeration value="bonificado"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="valorNoDisponibleType">
    <xs:restriction base="xs:string">
      <xs:pattern value="NO DISPONIBLE.*"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="numeroEtapaType">
    <xs:restriction base="xs:positiveInteger">
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="21"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="coordenadaGradoType">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="-180"/>
      <xs:maxInclusive value="180"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="altitudType">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="-200"/>
      <xs:maxInclusive value="9000"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="distanciaKmType">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="5000"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="velocidadMediaType">
    <xs:union>
      <xs:simpleType>
        <xs:restriction base="xs:decimal">
          <xs:minInclusive value="0"/>
          <xs:maxInclusive value="100"/>
        </xs:restriction>
      </xs:simpleType>
      <xs:simpleType>
        <xs:restriction base="valorNoDisponibleType"/>
      </xs:simpleType>
    </xs:union>
  </xs:simpleType>

  <xs:simpleType name="duracionType">
    <xs:union>
      <xs:simpleType>
        <xs:restriction base="xs:duration"/>
      </xs:simpleType>
      <xs:simpleType>
        <xs:restriction base="valorNoDisponibleType"/>
      </xs:simpleType>
    </xs:union>
  </xs:simpleType>

  <xs:complexType name="coordLongitudType">
    <xs:simpleContent>
      <xs:extension base="coordenadaGradoType">
        <xs:attribute name="unidad" type="xs:string" fixed="deg" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="coordLatitudType">
    <xs:simpleContent>
      <xs:extension base="coordenadaGradoType">
        <xs:attribute name="unidad" type="xs:string" fixed="deg" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="coordAltitudType">
    <xs:simpleContent>
      <xs:extension base="altitudType">
        <xs:attribute name="unidad" type="xs:string" fixed="m" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="coordenadasType">
    <xs:sequence>
      <xs:element name="coord_longitud" type="coordLongitudType"/>
      <xs:element name="coord_latitud" type="coordLatitudType"/>
      <xs:element name="coord_altitud" type="coordAltitudType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="lugarType">
    <xs:sequence>
      <xs:element name="nombre_lugar" type="xs:string"/>
      <xs:element name="coordenadas" type="coordenadasType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="distanciaKmConUnidadType">
    <xs:simpleContent>
      <xs:extension base="distanciaKmType">
        <xs:attribute name="unidad" type="xs:string" fixed="km" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="fotoType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="ruta" use="required">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:pattern value=".*\.(jpg|jpeg|png|gif|bmp|JPG|JPEG|PNG|GIF|BMP)"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="videoType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="ruta" use="required">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:pattern value=".*\.(mp4|avi|mkv|webm|MP4|AVI|MKV|WEBM)"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="sonidoType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="ruta" use="required">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:pattern value=".*\.(mp3|wav|ogg|MP3|WAV|OGG)"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="clasificadoType">
    <xs:sequence>
      <xs:element name="nombre_corredor" type="xs:string"/>
      <xs:element name="equipo" type="xs:string"/>
      <xs:element name="tiempo" type="duracionType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="clasificadoConDiferenciaType">
    <xs:sequence>
      <xs:element name="nombre_corredor" type="xs:string"/>
      <xs:element name="equipo" type="xs:string"/>
      <xs:element name="tiempo" type="duracionType"/>
      <xs:element name="diferencia" type="duracionType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="clasificadoGeneralType">
    <xs:sequence>
      <xs:element name="nombre_corredor" type="xs:string"/>
      <xs:element name="equipo" type="xs:string"/>
      <xs:element name="diferencia" type="duracionType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="equipoClasificadoType">
    <xs:sequence>
      <xs:element name="nombre_equipo" type="xs:string"/>
      <xs:element name="tiempo" type="duracionType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="equipoClasificadoConDiferenciaType">
    <xs:sequence>
      <xs:element name="nombre_equipo" type="xs:string"/>
      <xs:element name="tiempo" type="duracionType"/>
      <xs:element name="diferencia" type="duracionType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="etapa">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="numero" type="numeroEtapaType"/>
        <xs:element name="longitud_km">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="distanciaKmType">
                <xs:attribute name="unidad" type="xs:string" fixed="km" use="required"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="fecha" type="xs:date"/>
        <xs:element name="tiempo_ganador" type="duracionType"/>
        <xs:element name="velocidad_media">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="velocidadMediaType">
                <xs:attribute name="unidad" type="xs:string" fixed="km/h" use="required"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="desnivel_m">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="altitudType">
                <xs:attribute name="unidad" type="xs:string" fixed="m" use="required"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>

        <xs:element name="salida">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="lugar" type="lugarType"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="llegada">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="lugar" type="lugarType"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="referencias">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="referencia" type="xs:string" minOccurs="3" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="galeria_fotos">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="foto" type="fotoType" minOccurs="1" maxOccurs="5"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="galeria_videos">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="video" type="videoType" minOccurs="1" maxOccurs="3"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="galeria_sonidos">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="sonido" type="sonidoType" minOccurs="1" maxOccurs="3"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="hitos">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="puertos" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="puerto" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="nombre_puerto" type="xs:string"/>
                          <xs:element name="coordenadas" type="coordenadasType"/>
                          <xs:element name="distancia_km" type="distanciaKmConUnidadType"/>
                        </xs:sequence>
                        <xs:attribute name="categoria" type="categoriaPuertoType" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

              <xs:element name="sprints" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="sprint" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="nombre_sprint" type="xs:string"/>
                          <xs:element name="coordenadas" type="coordenadasType"/>
                          <xs:element name="distancia_km" type="distanciaKmConUnidadType"/>
                        </xs:sequence>
                        <xs:attribute name="tipo" type="tipoSprintType" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="puntos_anonimos" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="punto" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="coordenadas" type="coordenadasType"/>
                    <xs:element name="distancia_km" type="distanciaKmConUnidadType"/>
                  </xs:sequence>
                  <xs:attribute name="nombre" type="xs:string" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="clasificacion_etapa">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="primero" type="clasificadoType"/>
              <xs:element name="segundo" type="clasificadoConDiferenciaType"/>
              <xs:element name="tercero" type="clasificadoConDiferenciaType"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="clasificacion_general">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="primero" type="clasificadoType"/>
              <xs:element name="segundo_general" type="clasificadoGeneralType"/>
              <xs:element name="tercero_general" type="clasificadoGeneralType"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="clasificacion_equipos">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="primero_equipo" type="equipoClasificadoType"/>
              <xs:element name="segundo_equipo" type="equipoClasificadoConDiferenciaType"/>
              <xs:element name="tercero_equipo" type="equipoClasificadoConDiferenciaType"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="tipo" type="tipoEtapaType" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== uo300548/SEW/xml/etapaEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<etapa xmlns="http://www.uniovi.es"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.uniovi.es etapa.xsd"
       tipo="contrarreloj individual">
  <nombre>El Puerto de Santa María a Jerez de la Frontera</nombre>
  <numero>18</numero>
  <longitud_km unidad="km">32.1</longitud_km>
  <fecha>2026-09-10</fecha>
  <tiempo_ganador>PT35M22S</tiempo_ganador>
  <velocidad_media unidad="km/h">54.4</velocidad_media>
  <desnivel_m unidad="m">217</desnivel_m>

  <salida>
    <lugar>
      <nombre_lugar>Plaza de Toros de El Puerto de Santa María</nombre_lugar>
      <coordenadas>
        <coord_longitud unidad="deg">-6.23287</coord_longitud>
        <coord_latitud unidad="deg">36.59689</coord_latitud>
        <coord_altitud unidad="m">13</coord_altitud>
      </coordenadas>
    </lugar>
  </salida>

  <llegada>
    <lugar>
      <nombre_lugar>Jerez de la Frontera, zona de Avenida Alcalde Álvaro Domecq</nombre_lugar>
      <coordenadas>
        <coord_longitud unidad="deg">-6.13173</coord_longitud>
        <coord_latitud unidad="deg">36.69233</coord_latitud>
        <coord_altitud unidad="m">45</coord_altitud>
      </coordenadas>
    </lugar>
  </llegada>

  <referencias>
    <referencia>La Vuelta - Etapa 18 El Puerto de Santa María a Jerez de la Frontera - https://www.lavuelta.es/es/etapa-18</referencia>
    <referencia>La Vuelta - Clasificaciones oficiales de la etapa 18 - https://www.lavuelta.es/es/clasificaciones/etapa-18</referencia>
    <referencia>La Vuelta - Resumen de la etapa 18 - https://www.lavuelta.es/es/noticias/2026/etapa-18/kung-triunfa-en-jerez-mas-resiste/68541</referencia>
  </referencias>

  <galeria_fotos>
    <foto ruta="Puerto_Santa_Maria.jpg">Salida de la etapa en El Puerto de Santa María</foto>
    <foto ruta="Jerez_Frontera.jpg">Llegada en Jerez de la Frontera</foto>
    <foto ruta="Crono_Stage18.jpg">Resultados contrarreloj individual de la etapa 18</foto>
  </galeria_fotos>

  <galeria_videos>
    <video ruta="Resumen_Etapa18.mp4">Resumen de la etapa 18 de La Vuelta 2026</video>
  </galeria_videos>

  <galeria_sonidos>
    <sonido ruta="Podcast_Etapa18.mp3">Podcast sobre la etapa 18 de La Vuelta 2026</sonido>
  </galeria_sonidos>

  <hitos />

  <puntos_anonimos>
    <punto nombre="Corner 1">
      <coordenadas>
        <coord_longitud unidad="deg">-6.233140</coord_longitud>
        <coord_latitud unidad="deg">36.596555</coord_latitud>
        <coord_altitud unidad="m">13</coord_altitud>
      </coordenadas>
      <distancia_km unidad="km">0</distancia_km>
    </punto>

    <punto nombre="Corner 2">
      <coordenadas>
        <coord_longitud unidad="deg">-6.224500</coord_longitud>
        <coord_latitud unidad="deg">36.603800</coord_latitud>
        <coord_altitud unidad="m">24</coord_altitud>
      </coordenadas>
      <distancia_km unidad="km">1.6</distancia_km>
    </punto>

    <punto nombre="Corner 3">
      <coordenadas>
        <coord_longitud unidad="deg">-6.214000</coord_longitud>
        <coord_latitud unidad="deg">36.612900</coord_latitud>
        <coord_altitud unidad="m">30</coord_altitud>
      </coordenadas>
      <distancia_km unidad="km">3.9</distancia_km>
    </punto>

    <punto nombre="Corner 4">
      <coordenadas>
        <coord_longitud unidad="deg">-6.203000</coord_longitud>
        <coord_latitud unidad="deg">36.621500</coord_latitud>
        <coord_altitud unidad="m">38</coord_altitud>
      </coordenadas>
      <distancia_km unidad="km">6.1</distancia_km>
    </punto>

    <punto nombre="Corner 5">
      <coordenadas>
        <coord_longitud unidad="deg">-6.190000</coord_longitud>
        <coord_latitud unidad="deg">36.630000</coord_latitud>
        <coord_altitud unidad="m">47</coord_altitud>
      </coordenadas>
      <distancia_km unidad="km">8.7</distancia_km>
    </punto>

    <punto nombre="Corner 6">
      <coordenadas>
        <coord_longitud unidad="deg">-6.175000</coord_longitud>
        <coord_latitud unidad="deg">36.636570</coord_latitud>
        <coord_altitud unidad="m">56</coord_altitud>
      </coordenadas>
      <distancia_km unidad="km">10.7</distancia_km>
    </punto>

    <punto nombre="Corner 7">
      <coordenadas>
        <coord_longitud unidad="deg">-6.133080</coord_longitud>
        <coord_latitud unidad="deg">36.636570</coord_latitud>
        <coord_altitud unidad="m">69</coord_altitud>
      </coordenadas>
      <distancia_km unidad="km">16.2</distancia_km>
    </punto>

    <punto nombre="Corner 8">
      <coordenadas>
        <coord_longitud unidad="deg">-6.121000</coord_longitud>
        <coord_latitud unidad="deg">36.643000</coord_latitud>
        <coord_altitud unidad="m">78</coord_altitud>
      </coordenadas>
      <distancia_km unidad="km">18.5</distancia_km>
    </punto>

    <punto nombre="Corner 9">
      <coordenadas>
        <coord_longitud unidad="deg">-6.110000</coord_longitud>
        <coord_latitud unidad="deg">36.650000</coord_latitud>
        <coord_altitud unidad="m">82</coord_altitud>
      </coordenadas>
      <distancia_km unidad="km">20.4</distancia_km>
    </punto>

    <punto nombre="Corner 10">
      <coordenadas>
        <coord_longitud unidad="deg">-6.100000</coord_longitud>
        <coord_latitud unidad="deg">36.660000</coord_latitud>
        <coord_altitud unidad="m">90</coord_altitud>
      </coordenadas>
      <distancia_km unidad="km">22.1</distancia_km>
    </punto>

    <punto nombre="Corner 11">
      <coordenadas>
        <coord_longitud unidad="deg">-6.090000</coord_longitud>
        <coord_latitud unidad="deg">36.670000</coord_latitud>
        <coord_altitud unidad="m">98</coord_altitud>
      </coordenadas>
      <distancia_km unidad="km">23.8</distancia_km>
    </punto>

    <punto nombre="Corner 12">
      <coordenadas>
        <coord_longitud unidad="deg">-6.082000</coord_longitud>
        <coord_latitud unidad="deg">36.678000</coord_latitud>
        <coord_altitud unidad="m">105</coord_altitud>
      </coordenadas>
      <distancia_km unidad="km">25.4</distancia_km>
    </punto>

    <punto nombre="Corner 13">
      <coordenadas>
        <coord_longitud unidad="deg">-6.075270</coord_longitud>
        <coord_latitud unidad="deg">36.684950</coord_latitud>
        <coord_altitud unidad="m">112</coord_altitud>
      </coordenadas>
      <distancia_km unidad="km">26.7</distancia_km>
    </punto>

    <punto nombre="Corner 14">
      <coordenadas>
        <coord_longitud unidad="deg">-6.092000</coord_longitud>
        <coord_latitud unidad="deg">36.684000</coord_latitud>
        <coord_altitud unidad="m">109</coord_altitud>
      </coordenadas>
      <distancia_km unidad="km">25.8</distancia_km>
    </punto>

    <punto nombre="Corner 15">
      <coordenadas>
        <coord_longitud unidad="deg">-6.105000</coord_longitud>
        <coord_latitud unidad="deg">36.690000</coord_latitud>
        <coord_altitud unidad="m">103</coord_altitud>
      </coordenadas>
      <distancia_km unidad="km">27.2</distancia_km>
    </punto>

    <punto nombre="Corner 16">
      <coordenadas>
        <coord_longitud unidad="deg">-6.120000</coord_longitud>
        <coord_latitud unidad="deg">36.693000</coord_latitud>
        <coord_altitud unidad="m">82</coord_altitud>
      </coordenadas>
      <distancia_km unidad="km">28.9</distancia_km>
    </punto>

    <punto nombre="Corner 17">
      <coordenadas>
        <coord_longitud unidad="deg">-6.135000</coord_longitud>
        <coord_latitud unidad="deg">36.694000</coord_latitud>
        <coord_altitud unidad="m">60</coord_altitud>
      </coordenadas>
      <distancia_km unidad="km">30.5</distancia_km>
    </punto>

    <punto nombre="Corner 18">
      <coordenadas>
        <coord_longitud unidad="deg">-6.145000</coord_longitud>
        <coord_latitud unidad="deg">36.693000</coord_latitud>
        <coord_altitud unidad="m">54</coord_altitud>
      </coordenadas>
      <distancia_km unidad="km">31.6</distancia_km>
    </punto>

    <punto nombre="Corner 19">
      <coordenadas>
        <coord_longitud unidad="deg">-6.140000</coord_longitud>
        <coord_latitud unidad="deg">36.692000</coord_latitud>
        <coord_altitud unidad="m">49</coord_altitud>
      </coordenadas>
      <distancia_km unidad="km">31.9</distancia_km>
    </punto>

    <punto nombre="Corner 20">
      <coordenadas>
        <coord_longitud unidad="deg">-6.133000</coord_longitud>
        <coord_latitud unidad="deg">36.692000</coord_latitud>
        <coord_altitud unidad="m">45</coord_altitud>
      </coordenadas>
      <distancia_km unidad="km">32.1</distancia_km>
    </punto>
  </puntos_anonimos>

  <clasificacion_etapa>
    <primero>
      <nombre_corredor>Stefan Küng</nombre_corredor>
      <equipo>Tudor Pro Cycling Team</equipo>
      <tiempo>PT35M22S</tiempo>
    </primero>
    <segundo>
      <nombre_corredor>Callum Thornley</nombre_corredor>
      <equipo>Team Picnic PostNL</equipo>
      <tiempo>PT35M25S</tiempo>
      <diferencia>PT3S</diferencia>
    </segundo>
    <tercero>
      <nombre_corredor>João Almeida</nombre_corredor>
      <equipo>UAE Team Emirates-XRG</equipo>
      <tiempo>PT35M31S</tiempo>
      <diferencia>PT9S</diferencia>
    </tercero>
  </clasificacion_etapa>

  <clasificacion_general>
    <primero>
      <nombre_corredor>Enric Mas</nombre_corredor>
      <equipo>Movistar Team</equipo>
      <tiempo>PT60H45M58S</tiempo>
    </primero>
    <segundo_general>
      <nombre_corredor>Primož Roglič</nombre_corredor>
      <equipo>Red Bull-Bora-Hansgrohe</equipo>
      <diferencia>PT1H37M</diferencia>
    </segundo_general>
    <tercero_general>
      <nombre_corredor>Félix Gall</nombre_corredor>
